[package]
name = "crosswords"
version = "0.1.0"
authors = ["Kesavan Yogeswaran <hikes@google.com>"]
license = "Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/kesyog/crossword"

[dependencies]
anyhow = "1.0.38"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1.5"
dotenv = "0.15"
futures = "0.3.12"
governor = "0.3.2"
indicatif = { version = "0.15.0", features = ["improved_unicode"] }
reqwest = { version = "0.11", features = ["rustls-tls", "json", "gzip", "brotli"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }
